# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: katamoiran
description: Pen & Paper & Python
author: exposit
email: alto.dizi@gmail.com
url: http://exposit.github.io/katamoiran
baseurl: /katamoiran
#twitter_username: jekyllrb
github_username:  exposit

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
#exclude:
#  - Gemfile
#  - Gemfile.lock

# Configuration for jekyll
# NOTICE: GitHub forces to set `safe: true` in order to prohibit using plugins.
safe: true
#source: .
#destination: ./_site
#plugins: ./_plugins
#lsi: true
include: ['_pages', 'img', 'solos']

permalink: /blog/:year/:month/:title/

# Configuration for site


# Configuration for blog
lang: en
paginate: 4
columns: 3
date_format: "%B %d, %Y"
truncate_len: 200

# Configuration for asides/recent_posts.html
recent_posts: 5

# Configuration for navbar.html
navbar_list:
- name: Blog
  link: /
  dropdown: &dropdown
  - name: Archives
    link: /blog/archives.html
  - name: Categories
    link: /blog/categories.html
  - name: Tags
    link: /blog/tags.html
- name: Projects
  link: /projects/
- name: Solos
  link: /solos/index.html
  dropdown: &dropdown
  - name: Kyneros
    link: /solos/kyneros.html
  - name: Noir Nights
    link: /blog/categories.html
  - name: Ylinde
    link: /blog/tags.html
#- name: About
#  link: /about.html

# Configuration for bootstrap and color theme
# `bootstrap`:
# custom, original, amelia, cerulean, cyborg, journal,
# readable, simplex, slate, spacelab, spruce, superhero, united
bootstrap: custom
bootstrap_ver: 2.3.2
bootswatch_ver: 2.3.2
#bootstrap_ver: 3.3.7
#bootswatch_ver: 3.3.7

# Configuration for responsive break point when using 'custom'.
responsive_bp: 768

# Configuration for asides.html
# CAUTION: `themes` should be false to put the script.html at the bottom.
asides:
    about: true
    search: false
    themes: false
    recent_posts: true
    archive_tabs: true
    tweets: false
    github: false

# Configuration for pygments
# `pygments_style`:
# autumn, borland, bw, colorful, default, emacs, friendly, fruity,
# github, manni, monokai, murphy, native, pastie, perldoc, tango, trac, vs
pygments_style: gruvbox

# Configuration for jQuery
jquery_ver: 1.10.2
